FROM python:3.6-alpine
ADD . /code
WORKDIR /code
RUN apk update && \
        apk add --no-cache \
                pkgconfig \
                xmlsec \
                xmlsec-dev \
                g++ \
                libffi-dev \
                openssl-dev

RUN pip install -r requirements.txt
EXPOSE 8001
CMD gunicorn wsgi:app --bind 0.0.0.0:8001 --workers 10 --preload --timeout 180
