version: '2'
services:
    web:
        build:
           context: /shopping-final/farmers-market
           dockerfile: /shopping-final/farmers-market/Dockerfile
        network_mode: "host"
        ports:
                - "127.0.0.1:5000:5000"
        volumes:
            - .:/code
